// Database and utilities export
export { default as prisma } from './prisma';
export {
  checkDatabaseHealth,
  getDatabaseInfo,
  disconnectDatabase,
  withTransaction,
  executeRawQuery,
  getMigrationStatus,
  getDatabaseStats,
} from './database';

// Re-export Prisma types for convenience
export type {
  User,
  UserPreferences,
  ExternalConnection,
  JournalEntry,
  JournalReflection,
  DailyWin,
  LearningInsight,
  Task,
  TaskProject,
  TaskTimeEntry,
  TaskDependency,
  CalendarEvent,
  CalendarSource,
  EventReminder,
  EmailThread,
  EmailMessage,
  EmailAttachment,
  Contact,
  ContactEmail,
  ContactPhone,
  ContactAddress,
  DashboardWidget,
  AnalyticsData,
  UserInsight,
  ActivityLog,
  SyncStatus,
  CacheEntry,
  FeatureFlag,
  SchemaMigration,
  DataSubjectRequest,
  DataErasureLog,
  SyncConflict,
  QueryPerformanceLog,
  BackupMetadata,
} from '@prisma/client';